<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EventNotify', 'doctrine');

/**
 * BaseEventNotify
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $event_id
 * @property integer $mentee_id
 * @property integer $status
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method integer     getEventId()    Returns the current record's "event_id" value
 * @method integer     getMenteeId()   Returns the current record's "mentee_id" value
 * @method integer     getStatus()     Returns the current record's "status" value
 * @method timestamp   getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp   getUpdatedAt()  Returns the current record's "updated_at" value
 * @method EventNotify setId()         Sets the current record's "id" value
 * @method EventNotify setEventId()    Sets the current record's "event_id" value
 * @method EventNotify setMenteeId()   Sets the current record's "mentee_id" value
 * @method EventNotify setStatus()     Sets the current record's "status" value
 * @method EventNotify setCreatedAt()  Sets the current record's "created_at" value
 * @method EventNotify setUpdatedAt()  Sets the current record's "updated_at" value
 * 
 * @package    yoca
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventNotify extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_notify');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('event_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('mentee_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}