<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Registration', 'doctrine');

/**
 * BaseRegistration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $event_id
 * @property integer $mentee_id
 * @property integer $status
 * @property Event $Event
 * @property YocaUser $YocaUser
 * 
 * @method integer      getId()        Returns the current record's "id" value
 * @method integer      getEventId()   Returns the current record's "event_id" value
 * @method integer      getMenteeId()  Returns the current record's "mentee_id" value
 * @method integer      getStatus()    Returns the current record's "status" value
 * @method Event        getEvent()     Returns the current record's "Event" value
 * @method YocaUser     getYocaUser()  Returns the current record's "YocaUser" value
 * @method Registration setId()        Sets the current record's "id" value
 * @method Registration setEventId()   Sets the current record's "event_id" value
 * @method Registration setMenteeId()  Sets the current record's "mentee_id" value
 * @method Registration setStatus()    Sets the current record's "status" value
 * @method Registration setEvent()     Sets the current record's "Event" value
 * @method Registration setYocaUser()  Sets the current record's "YocaUser" value
 * 
 * @package    yoca
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registration');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('event_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('mentee_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $this->hasOne('YocaUser', array(
             'local' => 'mentee_id',
             'foreign' => 'id'));
    }
}