<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Event', 'doctrine');

/**
 * BaseEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $mentorid
 * @property integer $industry
 * @property integer $topic
 * @property string $capacity
 * @property string $booked
 * @property timestamp $datetime
 * @property integer $neighborhood
 * @property integer $address
 * @property string $status
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property EventTopic $EventTopic
 * @property EventAddress $EventAddress
 * @property YocaIndustry $YocaIndustry
 * @property YocaNeighborhood $YocaNeighborhood
 * @property Doctrine_Collection $Registration
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getMentorid()         Returns the current record's "mentorid" value
 * @method integer             getIndustry()         Returns the current record's "industry" value
 * @method integer             getTopic()            Returns the current record's "topic" value
 * @method string              getCapacity()         Returns the current record's "capacity" value
 * @method string              getBooked()           Returns the current record's "booked" value
 * @method timestamp           getDatetime()         Returns the current record's "datetime" value
 * @method integer             getNeighborhood()     Returns the current record's "neighborhood" value
 * @method integer             getAddress()          Returns the current record's "address" value
 * @method string              getStatus()           Returns the current record's "status" value
 * @method timestamp           getCreatedAt()        Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()        Returns the current record's "updated_at" value
 * @method EventTopic          getEventTopic()       Returns the current record's "EventTopic" value
 * @method EventAddress        getEventAddress()     Returns the current record's "EventAddress" value
 * @method YocaIndustry        getYocaIndustry()     Returns the current record's "YocaIndustry" value
 * @method YocaNeighborhood    getYocaNeighborhood() Returns the current record's "YocaNeighborhood" value
 * @method Doctrine_Collection getRegistration()     Returns the current record's "Registration" collection
 * @method Event               setId()               Sets the current record's "id" value
 * @method Event               setMentorid()         Sets the current record's "mentorid" value
 * @method Event               setIndustry()         Sets the current record's "industry" value
 * @method Event               setTopic()            Sets the current record's "topic" value
 * @method Event               setCapacity()         Sets the current record's "capacity" value
 * @method Event               setBooked()           Sets the current record's "booked" value
 * @method Event               setDatetime()         Sets the current record's "datetime" value
 * @method Event               setNeighborhood()     Sets the current record's "neighborhood" value
 * @method Event               setAddress()          Sets the current record's "address" value
 * @method Event               setStatus()           Sets the current record's "status" value
 * @method Event               setCreatedAt()        Sets the current record's "created_at" value
 * @method Event               setUpdatedAt()        Sets the current record's "updated_at" value
 * @method Event               setEventTopic()       Sets the current record's "EventTopic" value
 * @method Event               setEventAddress()     Sets the current record's "EventAddress" value
 * @method Event               setYocaIndustry()     Sets the current record's "YocaIndustry" value
 * @method Event               setYocaNeighborhood() Sets the current record's "YocaNeighborhood" value
 * @method Event               setRegistration()     Sets the current record's "Registration" collection
 * 
 * @package    yoca
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('mentorid', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('industry', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('topic', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('capacity', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('booked', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('datetime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('neighborhood', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('address', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EventTopic', array(
             'local' => 'topic',
             'foreign' => 'id'));

        $this->hasOne('EventAddress', array(
             'local' => 'address',
             'foreign' => 'id'));

        $this->hasOne('YocaIndustry', array(
             'local' => 'industry',
             'foreign' => 'id'));

        $this->hasOne('YocaNeighborhood', array(
             'local' => 'neighborhood',
             'foreign' => 'id'));

        $this->hasMany('Registration', array(
             'local' => 'id',
             'foreign' => 'event_id'));
    }
}