# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

login:
  url: /auth/login
  params: { module: auth, action: login }

logout:
  url: /auth/logout
  params: { module: auth, action: logout }
  
my_profile:
  url: /user/edit
  params: { module: user, action: edit }

my_account:
  url: /user/changePass
  params: { module: user, action: changePass }
  
become_a_mentee:
  url: /user/becomeMentee
  params: { module: user, action: becomeMentee }
  
become_a_mentor:
  url: /user/becomeMentor
  params: { module: user, action: becomeMentor }
  
mentorship_program:
  url: /event/index
  params: { module: event, action: index }

mentor_manage_event:
  url: /event/mentorMyEvents/:type/:page/:keyword
  params: { module: event, action: mentorMyEvents, type: my, page: 1, keyword: '' }
  
mentee_manage_event:
  url: /event/menteeMyEvents/:type/:page/:keyword
  params: { module: event, action: menteeMyEvents, type: my, page: 1, keyword: '' }

manage_events:
  url: /event/list/:type/:page/:keyword
  param: { module: event, action: list, type: upcoming, page: 1, keyword: '' }
  requirements:
    method: [get]
    
signup_event_notify:
  url: /event/signUpNotify/:eventId/:type/:page/:keyword    
  param: { module: event, action: signUpNotify, type: upcoming, page: 1, keyword: '' }

search_events:
  url: /event/search
  params: { module: event, action: search }
  requirements:
    method: [post]
    
show_event:
  url: /event/show/:id/:type/:page/:keyword
  param: { module: event, action: show, type: upcoming, page: 1, keyword: '' }
  requirements:
    id: \d+
    page: \d+

set_event_status:
  url: /event/setStatus/:id/:status/:type/:page/:keyword
  param: { module: event, action: setStatus, type: upcoming, page: 1, keyword: '' }
  requirements:
    id: \d+
    is_active: \d+

manage_users:
  url: /user/list/:type/:page/:keyword
  param: { module: user, action: list, type: Mentee, page: 1, keyword: '' }
  requirements:
    method: [get]

search_users:
  url: /user/search
  params: { module: user, action: search }
  requirements:
    method: [post]
  
show_user:
  url: /user/show/:id/:type/:page/:keyword
  param: { module: user, action: show, type: Mentee, page: 1, keyword: '' }
  requirements:
    id: \d+
    page: \d+

set_user_active:
  url: /user/setActive/:id/:is_active/:type/:page/:keyword
  param: { module: user, action: setActive, type: Mentee, page: 1, keyword: '' }
  requirements:
    id: \d+
    is_active: \d+
    
register_event:
  url: /register/register/:eventId/:type/:page/:keyword
  param: { module: register, action: register, type: upcoming, page: 1, keyword: '' }
  requirements:
    eventId: \d+
    
cancel_register:
  url: /register/cancel/:eventId/:type/:page/:keyword
  param: { module: register, action: cancel, type: upcoming, page: 1, keyword: '' }
  requirements:
    eventId: \d+

# default rules
homepage:
  url:   /
  param: { module: user, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
