# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

login:
  url: /auth/login
  params: { module: auth, action: login }

logout:
  url: /auth/logout
  params: { module: auth, action: logout }
  
my_profile:
  url: /user/edit
  params: { module: user, action: edit }

my_account:
  url: /user/reset_pass
  params: { module: user, action: resetPass }
  
become_a_mentee:
  url: /user/becomeMentee
  params: { module: user, action: becomeMentee }
  
become_a_mentor:
  url: /user/becomeMentor
  params: { module: user, action: becomeMentor }
  
mentorship_program:
  url: /event/index
  params: { module: event, action: index }

mentor_manage_event:
  url: /event/mentorMyEvents
  params: { module: event, action: mentorMyEvents }

manage_events:
  url: /event/list/:type/:page/:keyword
  param: { module: event, action: list, type: upcoming, page: 1, keyword: '' }

search_events:
  url: /event/search
  params: { module: event, action: search }

manage_users:
  url: /user/list/:type/:page/:keyword
  param: { module: user, action: list, type: Mentee, page: 1, keyword: '' }

search_users:
  url: /user/search
  params: { module: user, action: search }
  
show_user:
  url: /user/show/:id/:type/:page/:keyword
  param: { module: user, action: show, type: Mentee, page: 1, keyword: '' }  
  
activate_user:
  url: /user/activate/:id/:type/:page/:keyword
  param: { module: user, action: activate, type: Mentee, page: 1, keyword: '' }

deactivate_user:
  url: /user/deactivate/:id/:type/:page/:keyword
  param: { module: user, action: deactivate, type: Mentee, page: 1, keyword: '' }
  
# default rules
homepage:
  url:   /
  param: { module: user, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
