# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        YOCA | Young Overseas Chinese Associations 
    description:  YOCA | Young Overseas Chinese Associations
    author:       YOCA
    keywords:     YOCA
    language:     en
    robots:       index, follow
    viewport:     width=device-width, initial-scale=1.0

  stylesheets:    [yoca.css?v=2]

  javascripts:    [libs/modernizr.js, libs/selectivizr.js, navigation.js, bootstrap/bootstrap.js, plugins/dataTables/jquery.datatables.min.js]

  has_layout:     true
  layout:         layout
