<?php

/**
 * EventNotifyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventNotifyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventNotifyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventNotify');
    }
    
    public function isSignedUp($eventId, $menteeId, $status){
    	$notify = $this->createQuery('n')
    	->select('count(n.id)')
    	->where('n.event_id = ? and n.mentee_id = ?', array($eventId, $menteeId))
    	->setHydrationMode(Doctrine::HYDRATE_SINGLE_SCALAR)
    	->execute();
    	
    	return $notify>0? true:false;
    }
}