<?php

/**
 * Event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    yoca
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Event extends BaseEvent
{
	public function save(Doctrine_Connection $con = null){
		if($this->isNew()){
			$this->setMentorid(sfContext::getInstance()->getUser()->getAttribute('userid'));
			$this->setBooked(0);
			$this->setStatus(0);
			$this->setCreatedAt(date("Y-m-d H:i:s"));
		}
		
		parent::save($con);
	}
}
