<?php

/**
 * EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Event');
    }
    
    public function findMentorEvents($mentorId){
    	return self::getInstance()->createQuery('e')
		->leftJoin('e.YocaIndustry i')
    	->where('e.mentorid = ? and e.status <> 3', $mentorId)
    	->execute();
    }
    
    public function findMenteeEvents($menteeId){
    	return self::getInstance()->createQuery('e')
    	->leftJoin('e.YocaIndustry i')
    	->leftJoin('e.Registration r')
    	->where('r.mentee_id = ?', $menteeId)
    	->execute();
    }
}