<?php

/**
 * EventAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventAddressTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventAddress');
    }
}