<?php

/**
 * EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Event');
    }
    
    public function findMentorEvents($mentorId){
    	return self::getInstance()->createQuery('e')
    	->leftJoin('e.EventTopic t')
		->leftJoin('e.YocaIndustry i')
		->leftJoin('e.YocaNeighborhood n')
		->leftJoin('e.EventAddress a')
		->leftJoin('e.YocaUser u')
		->select('e.*, t.name, i.name, n.name, a.name, u.mentor_id')
    	->where('e.mentorid = ? and e.status <> 3', $mentorId)
    	->orderBy('e.datetime asc')
    	->setHydrationMode(Doctrine::HYDRATE_ARRAY)
    	->execute();
    }
    
    public function findMenteeEvents($menteeId){
    	return self::getInstance()->createQuery('e')
    	->leftJoin('e.YocaIndustry i')
    	->leftJoin('e.Registration r')
    	->where('r.mentee_id = ? and r.status = ?', array($menteeId, 1))
    	->execute();
    }
    
    public function findEvent($id){
    	return self::getInstance()->createQuery('e')
    	->leftJoin('e.EventTopic t')
    	->leftJoin('e.YocaIndustry i')
    	->leftJoin('e.YocaNeighborhood n')
    	->leftJoin('e.EventAddress a')
    	->leftJoin('e.YocaUser u')
    	->where('e.id = ?', $id)
    	->fetchOne();
    }
}