<?php

/**
 * EventTopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventTopic');
    }
}