<?php

/**
 * RegistrationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegistrationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegistrationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Registration');
    }
    
	public function getMenteeRegs($eventId, $menteeId, $status){
		return $this->createQuery('r')
		->where('r.mentee_id = ? and r.event_id = ? and r.status = ?', array($menteeId, $eventId, $status))
		->setHydrationMode(Doctrine::HYDRATE_ARRAY_SHALLOW)
		->execute();
	} 
	
	public function getRegsByIdAndStatus($eventId, $status){
		return $this->createQuery('r')
		->where('r.event_id = ? and r.status = ?', array($eventId, $status))
		->setHydrationMode(Doctrine::HYDRATE_ARRAY_SHALLOW)
		->execute();
	}
	
	public function setRegStatus($eventIdArray, $status){
		$this->createQuery('r')
		->update()
		->set('r.status', $status)
		->whereIn('r.id', $eventIdArray)
		->execute();
	}
}