<?php

/**
 * RegistrationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegistrationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegistrationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Registration');
    }
    
	public static function getMenteeRegistrations($eventId, $menteeId){
		return self::getInstance()
		->createQuery()
		->where('mentee_id = ? and event_id = ?', array($menteeId, $eventId))
		->execute();
	} 
}