<?php

/**
 * YocaUserSchoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class YocaUserSchoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object YocaUserSchoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('YocaUserSchool');
    }
}