<?php

/**
 * YocaSchoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class YocaSchoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object YocaSchoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('YocaSchool');
    }
}