<?php

/**
 * YocaIndustryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class YocaIndustryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object YocaIndustryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('YocaIndustry');
    }
    
    public function getIndustryForMentee(){
    	return $this->createQuery('i')
    	->where("i.type = 'mentee'")
    	->execute();
    }
    
    public function getIndustryForMentor(){
    	return $this->createQuery('i')
    	->where("i.type = 'mentor'")
    	->execute();
    }
}