<?php

/**
 * YocaUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class YocaUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object YocaUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('YocaUser');
    }
}