<?php

/**
 * YocaNeighborhoodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class YocaNeighborhoodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object YocaNeighborhoodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('YocaNeighborhood');
    }
}