<?php

/**
 * YocaWorkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class YocaWorkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object YocaWorkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('YocaWork');
    }
}