<?php

/**
 * YocaUserWorkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class YocaUserWorkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object YocaUserWorkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('YocaUserWork');
    }
}