<?php

/**
 * YocaUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    yoca
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class YocaUser extends BaseYocaUser
{
	public function save(Doctrine_Connection $con = null){
		if ($this->isNew())
		{
			$passHash = sfContext::getInstance()->getUser()->generateHash($this->getPassword());
			
			$this->setPassword($passHash);
			$this->setCreatedAt(date("Y-m-d H:i:s"));
		}else{
			if(strlen($this->getEnglishName()) === 0){
				$this->setEnglishName(null);
			}
			
			if(strlen($this->getPhone()) === 0){
				$this->setPhone(null);
			}
			
			if(strlen($this->getWechat()) === 0){
				$this->setWechat(null);
			}
			
			if(strlen($this->getSchool()) === 0){
				$this->setSchool(null);
			}
			
			if(strlen($this->getMajor()) === 0){
				$this->setMajor(null);
			}
			
			$this->setIndustryId(is_array($this->getIndustryId())?implode(',', $this->getIndustryId()):$this->getIndustryId());
			if(strlen($this->getIndustry()) === 0){
				$this->setIndustry(null);
			}
			if(strlen($this->getSubIndustry()) === 0){
				$this->setSubIndustry(null);
			}
			
			$this->setExpectationId(is_array($this->getExpectationId())?implode(',', $this->getExpectationId()):$this->getExpectationId());
			if(strlen($this->getExpectation()) === 0){
				$this->setExpectation(null);
			}
			
			if(strlen($this->getAge()) === 0){
				$this->setAge(null);
			}
			
			if(strlen($this->getNeighborhood()) === 0){
				$this->setNeighborhood(null);
			}
			
			if(strlen($this->getOrganization()) === 0){
				$this->setOrganization(null);
			}	
		}
		
		return parent::save($con);
	}
}
