<?php

/**
 * YocaMajorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class YocaMajorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object YocaMajorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('YocaMajor');
    }
}