<?php

/**
 * YocaUserDescriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class YocaUserDescriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object YocaUserDescriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('YocaUserDescription');
    }
}